import os
import json
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def build_fallback(signal_json: dict) -> dict:
    action = signal_json.get("action", "HOLD")
    probs = signal_json.get("probabilities", {})

    return {
        "model_name": "GPT",
        "ticker": signal_json.get("ticker", "UNKNOWN"),
        "suggestion": action,
        "summary": f"The model suggests {action} over the next {signal_json.get('horizon_days', 20)} days.",
        "reasoning": [
            f"SELL probability: {probs.get('SELL', 0)}",
            f"HOLD probability: {probs.get('HOLD', 0)}",
            f"BUY probability: {probs.get('BUY', 0)}"
        ],
        "risk_warning": [
            "OpenAI API unavailable.",
            "Fallback explanation generated locally."
        ],
        "confidence_level": "MEDIUM"
    }


def explain_signal_with_gpt(signal_json: dict) -> dict:
    system_prompt = """
You are a financial AI assistant.

You receive a JSON signal generated by a machine learning model.
You must explain the signal in a user-friendly way.

Return JSON only.

Required fields:
model_name
ticker
suggestion
summary
reasoning
risk_warning
confidence_level
"""

    user_prompt = f"""
Model signal:

{json.dumps(signal_json, indent=2)}

Return explanation JSON only.
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            response_format={"type": "json_object"},
            max_tokens=500
        )

        content = response.choices[0].message.content
        result = json.loads(content)

        result["model_name"] = "GPT"
        return result

    except Exception as e:
        print("GPT API error:", repr(e))
        return build_fallback(signal_json)